config/routes.rb
Rails.application.routes.draw do
  
  resources :charges, only: [:new, :create]

  devise_for :users
  
  resources :users, only: [:show]
  
  resources :wikis do
    resources :collaborators, only: [:index, :new, :create]
  end
  
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :collaborate_wikis, through: :collaborators, source: :wiki
  
  before_save {self.email = email.downcase if email.present? }
  after_initialize :init
  
  enum role: [:member, :admin, :premium]
  
  def init
    self.role ||= :member
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :collaborate_users, through: :collaborators, source: :user
  
  default_scope {order('created_at DESC')}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to do that."
    redirect_to root_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
   
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )
   
    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    if (flash[:notice])
      current_user.update_attribute(:role, "premium")
    end
    redirect_to user_path(current_user)
   
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    def index
        @wiki = Wiki.find(params[:wiki_id])
        @collaborators = @wiki.collaborate_users.all
    end
    
    def new
        @wiki = Wiki.find(params[:wiki_id])
        authorize(@wiki.collaborators)
    end
    
    def create
        wiki = Wiki.find(params[:wiki_id])
        collaborators = []
        wiki.collaborators.destroy_all
        params[:collaborators].each do |c|
            collaborators << {
                wiki_id: wiki.id,
                user_id: c}
        end
        Collaborator.create(collaborators)
        redirect_to wiki_collaborators_path(wiki)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index, :about]
  
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    skip_before_filter :authenticate_user!, only: [:index, :show]
    after_action :verify_policy_scoped, only: :index
    
    def index
        @wikis = policy_scope(Wiki)
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def new
        @wiki = Wiki.new
    end
    
    def create
        @wiki = Wiki.create(wiki_params)
        @wiki.user = current_user
        
        if @wiki.save
            flash[:notice] = "Wiki was saved."
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error saving the wiki. Please try again."
            render :new
        end
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
        @wiki = Wiki.find(params[:id])
        authorize @wiki
        @wiki.assign_attributes(wiki_params)
        
        if @wiki.save
            flash[:notice] = "Wiki was updated"
            redirect_to @wiki
        else
            flash.now[:alert] = "Error saving wiki. Please try again."
            render :edit
        end
    end
    
    def destroy
        @wiki = Wiki.find(params[:id])
        authorize @wiki
        
        if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to wikis_path
        else
            flash.now[:alert] = "There was an error deleting the wiki"
            render :show
        end
    end
    
    private
    
    def wiki_params
        params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = {
            filter_html: true,
            prettify: true,
            hard_wrap: true,
            safe_links_only: true,
            space_after_headers: true,
            fenced_code_blocks: true
        }
        
        extensions = {
            autolink: true,
            superscript: true
        }
        
        renderer = Redcarpet::Render::HTML.new(options)
        @markdown ||= Redcarpet::Markdown.new(renderer, extensions)
        
        @markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def user_can_upgrade?(user)
        current_user == user && current_user.role == 'member'
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <h4>Click the button!</h4>
    
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>All Collaborators for <%= @wiki.title %> Wiki </h1>

<ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborate_users %></ul>

<p><%= link_to "Return to Wiki", wiki_path(@wiki), class: 'btn btn-success' %></p>

app/views/collaborators/new.html.erb
<h2>Add collaborators to <%= @wiki.title %>:</h2>

<%= form_tag(wiki_collaborators_path(wiki_id: @wiki), method: :post) do %>
    <table class="users_table">
        <tr>
            <th>User</th>
            <th>Give Access?</th>
        </tr>
        <% User.all.each do |user| %>
            <tr>
                <td><%= user.email %></td>
                <td><%= check_box_tag('collaborators[]', user.id, @wiki.collaborate_users.include?(user), {multiple: true}) %></td>
            </tr>
        <% end %>
    </table>
    <p><%= submit_tag("Save", class: 'btn btn-success', data: {confirm: "Are you sure you want to add/remove these collaborators?"}) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
    
    <div class="pull-right user-info">
      <% if user_signed_in? %>
        Signed in as: <strong><%= link_to current_user.email, user_path(current_user) %></strong> | 
        
        <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
    </ul>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.email if @user.email%></h1>
<h3>User type: <%= @user.role %></h3>

<!-- Btn should only appear is standard member looking at their own profile -->
<% if user_can_upgrade?(@user) %>
    <%= link_to "Upgrade to Premium Account!", new_charge_path, class: 'btn btn-success' %>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Blocipedia: Social, Markdown Wikis</h1>
    <h3>Create and share Markdown Wikis</h3>
    <p>
        <% if !user_signed_in? %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-success' %> <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-default' %>
        <% else %>
            <%= link_to "New Wiki", new_wiki_path, :class => 'btn btn-success' %>
        <% end %>
    </p>
</div>

<div class="row icons">
    <div class="col-md-6">
       <p>Create as many public wikis as you want!</p>
       <span class="glyphicon glyphicon-fire"></span><br>
       Free Plan
    </div>
    <div class="col-md-6">
        <p>Create private wikis!</p>
        <span class="glyphicon glyphicon-euro"></span><br>
        Premium Plan
    </div>
</div>

app/views/wikis/_collaborator.html.erb
<li><%= link_to collaborator.email, user_path(collaborator) %></li>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter wiki body" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
                <%= f.check_box :private %> Private wiki
            <% end %>
        </div>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="col-md-6">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>

<div class="row">
    <div class="col-md-8">
        <% @wikis.each do |wiki| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to wiki.title, wiki %>
                        <% if wiki.private %>
                            <small><em>Private wiki</em></small>
                        <% end %>
                    </h4>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="col-md-6">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/show.html.erb
<h1>
    <%= @wiki.title %> <br>
    <small>
        <% if @wiki.private %><em>Private wiki</em><br><% end %>
        submitted <%= time_ago_in_words(@wiki.created_at) %> ago
    </small>
    <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
</h1>
<p><%= markdown(@wiki.body) %> </p>
<p>Created by: <%= @wiki.user.email %></p>
<div>
    <% if @wiki.private %>
        <h4>Collaborators:</h4>
        <p><%= link_to "Add/Remove collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-default' %></p>
        <ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborate_users %></ul>
    <% end %>
</div>